### ISSUE TITLE
__atomic_load_8 building issue

### ISSUE THREAD

**Issue by CanDuru4** [Qengineering/Install-OpenCV-Raspberry-Pi-32-bits#3]
Hi,

I have a raspberry pi 4 models with 32-bit OS. I arranged my RAM and SWAP memory before building it. However, I am getting an error called "undefined reference to `__atomic_load_8'". I added the screenshot. I will appreciate your help.

<img width="579" alt="Ekran Resmi 2023-07-18 14 15 06" src="https://github.com/Qengineering/Install-OpenCV-Raspberry-Pi-32-bits/assets/73294429/a001eb95-1862-4766-af0f-263362556df8">

<img width="1724" alt="Ekran Resmi 2023-07-18 14 14 43" src="https://github.com/Qengineering/Install-OpenCV-Raspberry-Pi-32-bits/assets/73294429/8a12726e-f006-4b8b-8be7-dff2096f04f1">

**Comment by Qengineering** [comment]
@CanDuru4,

Very recently the famous  **__atomic_load_8** error pops up again.
Please check the cmake command. It should have these flags:
```
-D CMAKE_CXX_FLAGS=-latomic \
-D OPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic \
```
I've already updated the GitHub repo 3 days ago with these flags.

**Comment by CanDuru4** [comment]
I tried to build it a few hours ago. So, it was after your update. I am trying again. I will inform you about the process.

**Comment by CanDuru4** [comment]
I am still getting the same error.
<img width="1728" alt="Ekran Resmi 2023-07-18 15 52 41" src="https://github.com/Qengineering/Install-OpenCV-Raspberry-Pi-32-bits/assets/73294429/6e80d396-94c6-43e7-9768-80006b8167f0">

**Comment by Qengineering** [comment]
I need some more information.
Which OS are you using Buster/Bullseye?
Is it a clean OS, or is there already additional software installed?
I like to reproduce your issue here at the office.

**Comment by CanDuru4** [comment]
Of course. Sorry for not giving them earlier. I am using Debian Bullseye since May 3, 2023. It is a clean OS. I just installed it. I am using Raspberry Pi 4.
<img width="832" alt="Ekran Resmi 2023-07-18 16 11 47" src="https://github.com/Qengineering/Install-OpenCV-Raspberry-Pi-32-bits/assets/73294429/1b9b7647-3643-4391-aea9-2c2991c7f261">

**Comment by Qengineering** [comment]
@CanDuru4,

I've reproduced your issue. It only happens with a 32-bit OS. No matter if you have an RPi 3, or 4.
It going to be a nasty one. Most common solutions don't work.
I'll be back!

see also https://github.com/scipy/scipy/issues/17670#issuecomment-1371925488 for an explanation, not a solution

**Comment by CanDuru4** [comment]
Thank you so much for your help. I am waiting.

**Comment by Qengineering** [comment]
Dear @CanDuru4,

Thanks for your patience.
It took some time the debug the error. Most time-consuming part is the compilation over and over again to see if the fix is working.
To get OpenCV installed on your 32-bit system you have two alterations to make.
## 1
Remove 
```
-D CMAKE_CXX_FLAGS=-latomic \
-D OPENCV_EXTRA_EXE_LINKER_FLAGS=-latomic \
```
and replace it with
```
-D CMAKE_SHARED_LINKER_FLAGS=-latomic \
```
in the cmake command line. 
I have already updated my repo with this modification.
## 2
Second part is modifying `opencv/modules/calib3d/CMakeList.txt`
Add `${CMAKE_SHARED_LINKER_FLAGS}` in the link line at the end of the file.
The whole file must look like this:
```
set(the_description "Camera Calibration and 3D Reconstruction")

ocv_add_dispatched_file(undistort SSE2 AVX2)

set(debug_modules "")
if(DEBUG_opencv_calib3d)
  list(APPEND debug_modules opencv_highgui)
endif()
ocv_define_module(calib3d opencv_imgproc opencv_features2d opencv_flann ${debug_modules}
    WRAP java objc python js
)
ocv_target_link_libraries(${the_module} ${LAPACK_LIBRARIES} ${CMAKE_SHARED_LINKER_FLAGS})
```

I've [made a pull request](https://github.com/opencv/opencv/pull/24031).

**Comment by CanDuru4** [comment]
Hi,

Sorry for the late reply. This solution worked for me. Thank you so much for your help. Finally, I am able to work with OpenCV.
